name: Update README

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - List files
      run: ls -la

    - name: Update README.md
      run: |
        echo "## Latest Update" >> README.md
        echo "Changes were pushed on $(date)" >> README.md

    - name: Debug - Show README.md
      run: cat README.md

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
        git add README.md
        git commit -m 'Update README.md with latest changes'
        git push